spring:
  application:
    name: kubetest-ui
server:
  port: 9090
  
kubetest:
  url:
    one: http://kubetestone-cluster.default.svc.cluster.local:8081/info
    two: http://kubetesttwo-cluster.default.svc.cluster.local:8082/info